name=(input("hey whats your name? "))
a=(name)
print("well thats a nice one, nice to meet you ", a)
color=(input("whats your fav color? "))
b=(color)
print(b,"? thats a nice color i like it too")
food=(input("what about food, give me your favorite "))
c=(food)
print(c,"ohh yes that sounds yummy. lets go get some now!")